"""Recording reverse proxy: capture requests to the Anthropic API, then forward them.

This is one of two shared modules in the repo. It exists for a single reason:
**you cannot prove a tool is disabled by looking at the model's output; you can
only prove it by looking at the wire request and seeing the tool is not there.**

Usage:

    from recording_proxy import RecordingProxy

    with RecordingProxy() as proxy:
        env = {"ANTHROPIC_BASE_URL": proxy.base_url}   # all three modes honor this
        ...  # run claude -p / Agent SDK / the client SDK under this env
    for req in proxy.requests:
        print(req["body"]["tools"])

Implementation notes:

* This is a **reverse proxy, not a MITM**. The client speaks plain HTTP to
  127.0.0.1 and the proxy speaks HTTPS to api.anthropic.com. That means
  **no CA certificate to install** — far lighter than the mitmproxy route.
* Standard library only, no third-party dependencies.
* Auth headers (OAuth bearer or x-api-key) are forwarded untouched, so the
  claude.ai login that `claude` already has works as-is. No API key needed.
* Responses are relayed chunk by chunk with no buffering — otherwise streaming
  SSE responses would stall.
"""

from __future__ import annotations

import http.client
import json
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any

UPSTREAM_HOST = "api.anthropic.com"

# Hop-by-hop headers are meaningful only for a single connection leg. They must
# be dropped when forwarding, or they collide with the transport headers we
# regenerate ourselves.
_HOP_BY_HOP = {
    "connection", "keep-alive", "transfer-encoding", "upgrade",
    "proxy-authenticate", "proxy-authorization", "te", "trailers",
}


class RecordingProxy:
    """A reverse proxy on an ephemeral port that records every request."""

    def __init__(self, upstream: str = UPSTREAM_HOST) -> None:
        self.upstream = upstream
        self.requests: list[dict[str, Any]] = []
        self._lock = threading.Lock()
        self._server: ThreadingHTTPServer | None = None
        self._thread: threading.Thread | None = None

    @property
    def base_url(self) -> str:
        assert self._server is not None, "proxy is not running"
        return f"http://127.0.0.1:{self._server.server_address[1]}"

    def __enter__(self) -> RecordingProxy:
        proxy = self

        class Handler(BaseHTTPRequestHandler):
            protocol_version = "HTTP/1.1"

            def log_message(self, format: str, *args: Any) -> None:
                pass  # silence the default stderr access log

            def _forward(self) -> None:
                length = int(self.headers.get("Content-Length") or 0)
                body = self.rfile.read(length) if length else b""
                proxy._record(self.command, self.path, body)

                # Host must be regenerated by http.client for the upstream;
                # forwarding the local address would break the request.
                headers = {
                    k: v for k, v in self.headers.items()
                    if k.lower() not in _HOP_BY_HOP and k.lower() != "host"
                }
                conn = http.client.HTTPSConnection(proxy.upstream, timeout=600)
                try:
                    conn.request(self.command, self.path, body=body, headers=headers)
                    resp = conn.getresponse()
                    self.send_response(resp.status)
                    for key, value in resp.getheaders():
                        # Drop Content-Length: we relay with chunked encoding.
                        if key.lower() in _HOP_BY_HOP or key.lower() == "content-length":
                            continue
                        self.send_header(key, value)
                    self.send_header("Transfer-Encoding", "chunked")
                    self.end_headers()
                    while True:
                        chunk = resp.read(4096)
                        if not chunk:
                            break
                        # Hand-rolled chunked encoding, flushed per chunk, so SSE
                        # events reach the client live instead of piling up.
                        self.wfile.write(b"%X\r\n" % len(chunk) + chunk + b"\r\n")
                        self.wfile.flush()
                    self.wfile.write(b"0\r\n\r\n")
                    self.wfile.flush()
                except (BrokenPipeError, ConnectionResetError):
                    # Clients often disconnect early once they have what they
                    # need (common with SSE). The request body is already
                    # recorded, so no evidence is lost here.
                    pass
                finally:
                    conn.close()

            do_GET = do_POST = do_PUT = do_DELETE = _forward

        self._server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self._thread = threading.Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()
        return self

    def __exit__(self, *exc: object) -> None:
        if self._server is not None:
            self._server.shutdown()
            self._server.server_close()

    def _record(self, method: str, path: str, body: bytes) -> None:
        try:
            parsed = json.loads(body) if body else None
        except (json.JSONDecodeError, UnicodeDecodeError):
            parsed = None
        with self._lock:
            self.requests.append({"method": method, "path": path, "body": parsed})

    # ---- assertion helpers -------------------------------------------

    def tools_offered(self, *names: str) -> list[str]:
        """Which of `names` were *shipped to the model* in any captured request.

        This reads the request's `tools[]` array, i.e. what the model was
        allowed to use. Contrast with `tool_uses`, which reads what the model
        actually did.

        Why match on both `name` and `type`? Because the same capability takes
        different shapes across modes:

        * `claude -p` / Agent SDK: sent as an ordinary custom tool, just
          `{"name": "WebSearch", "input_schema": ...}` — **no type field**.
        * Direct API: sent as an Anthropic server-side tool, shaped like
          `{"type": "web_search_20260209", "name": "web_search"}`.

        Probing for only one shape silently misses the other — the first
        cross-mode trap this repo recorded.
        """
        wanted = {n.lower() for n in names}
        found: list[str] = []
        for req in self.requests:
            body = req.get("body") or {}
            for tool in body.get("tools") or []:
                name = (tool.get("name") or "").lower()
                type_ = (tool.get("type") or "").lower()
                if name in wanted or any(type_.startswith(w) for w in wanted):
                    found.append(tool.get("type") or tool.get("name"))
        return found

    def tool_uses(self, *names: str) -> list[dict[str, Any]]:
        """Which of `names` the model *actually invoked*, as full tool_use blocks.

        Reads the conversation history rather than the tool list. When the model
        calls a tool, that call is replayed in `messages[*].content[*]` of the
        next request — an agentic loop always sends one more request to hand
        back the `tool_result`, so the call is always captured.

        Whole blocks are returned rather than just names so callers can inspect
        `input`; that is how `features/web_search/behavior.py` spots a model
        reaching the network through `Bash` + `curl` once the web tools are gone.

        Names are matched exactly and case-insensitively. Unlike `tools_offered`
        there is no type-prefix matching, because a tool_use block carries the
        tool's name, never its declaration type.
        """
        wanted = {n.lower() for n in names}
        found: list[dict[str, Any]] = []
        for req in self.requests:
            for message in (req.get("body") or {}).get("messages") or []:
                content = message.get("content")
                if not isinstance(content, list):
                    continue  # a plain string turn holds no tool calls
                for block in content:
                    if block.get("type") != "tool_use":
                        continue
                    if (block.get("name") or "").lower() in wanted:
                        found.append(block)
        return found

    def tool_results(self) -> dict[str, dict[str, Any]]:
        """Map every `tool_use_id` to the `tool_result` block that answered it.

        Pairing a call with its result is what separates *attempted* from
        *executed*. A harness can accept a tool call and then refuse to run it
        — in non-interactive mode there is nobody to approve a permission
        prompt, so the result comes back with `is_error: true` and a message
        about permissions, and the tool never reached the network.

        Later results win, so a retried call reflects its final outcome.
        """
        results: dict[str, dict[str, Any]] = {}
        for req in self.requests:
            for message in (req.get("body") or {}).get("messages") or []:
                content = message.get("content")
                if not isinstance(content, list):
                    continue
                for block in content:
                    if block.get("type") == "tool_result" and block.get("tool_use_id"):
                        results[block["tool_use_id"]] = block
        return results

    def dump(self, path: str) -> None:
        """Write captured requests as JSONL — the raw evidence for manual review."""
        with open(path, "w", encoding="utf-8") as fh:
            for req in self.requests:
                fh.write(json.dumps(req, ensure_ascii=False) + "\n")
