"""Recording reverse proxy: capture requests to the Anthropic API, then forward them.

This is one of two shared modules in the repo. It exists for a single reason:
**you cannot prove a tool is disabled by looking at the model's output; you can
only prove it by looking at the wire request and seeing the tool is not there.**

Usage:

    from recording_proxy import RecordingProxy

    with RecordingProxy() as proxy:
        env = {"ANTHROPIC_BASE_URL": proxy.base_url}   # all three modes honor this
        ...  # run claude -p / Agent SDK / the client SDK under this env
    for req in proxy.requests:
        print(req["body"]["tools"])

Implementation notes:

* This is a **reverse proxy, not a MITM**. The client speaks plain HTTP to
  127.0.0.1 and the proxy speaks HTTPS to api.anthropic.com. That means
  **no CA certificate to install** — far lighter than the mitmproxy route.
* Standard library only, no third-party dependencies.
* Auth headers (OAuth bearer or x-api-key) are forwarded untouched, so the
  claude.ai login that `claude` already has works as-is. No API key needed.
* Responses are relayed chunk by chunk with no buffering — otherwise streaming
  SSE responses would stall.
"""

from __future__ import annotations

import http.client
import json
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any

UPSTREAM_HOST = "api.anthropic.com"

# Hop-by-hop headers are meaningful only for a single connection leg. They must
# be dropped when forwarding, or they collide with the transport headers we
# regenerate ourselves.
_HOP_BY_HOP = {
    "connection", "keep-alive", "transfer-encoding", "upgrade",
    "proxy-authenticate", "proxy-authorization", "te", "trailers",
}


class RecordingProxy:
    """A reverse proxy on an ephemeral port that records every request."""

    def __init__(self, upstream: str = UPSTREAM_HOST) -> None:
        self.upstream = upstream
        self.requests: list[dict[str, Any]] = []
        self._lock = threading.Lock()
        self._server: ThreadingHTTPServer | None = None
        self._thread: threading.Thread | None = None

    @property
    def base_url(self) -> str:
        assert self._server is not None, "proxy is not running"
        return f"http://127.0.0.1:{self._server.server_address[1]}"

    def __enter__(self) -> RecordingProxy:
        proxy = self

        class Handler(BaseHTTPRequestHandler):
            protocol_version = "HTTP/1.1"

            def log_message(self, format: str, *args: Any) -> None:
                pass  # silence the default stderr access log

            def _forward(self) -> None:
                length = int(self.headers.get("Content-Length") or 0)
                body = self.rfile.read(length) if length else b""
                proxy._record(self.command, self.path, body)

                # Host must be regenerated by http.client for the upstream;
                # forwarding the local address would break the request.
                headers = {
                    k: v for k, v in self.headers.items()
                    if k.lower() not in _HOP_BY_HOP and k.lower() != "host"
                }
                conn = http.client.HTTPSConnection(proxy.upstream, timeout=600)
                try:
                    conn.request(self.command, self.path, body=body, headers=headers)
                    resp = conn.getresponse()
                    self.send_response(resp.status)
                    for key, value in resp.getheaders():
                        # Drop Content-Length: we relay with chunked encoding.
                        if key.lower() in _HOP_BY_HOP or key.lower() == "content-length":
                            continue
                        self.send_header(key, value)
                    self.send_header("Transfer-Encoding", "chunked")
                    self.end_headers()
                    while True:
                        chunk = resp.read(4096)
                        if not chunk:
                            break
                        # Hand-rolled chunked encoding, flushed per chunk, so SSE
                        # events reach the client live instead of piling up.
                        self.wfile.write(b"%X\r\n" % len(chunk) + chunk + b"\r\n")
                        self.wfile.flush()
                    self.wfile.write(b"0\r\n\r\n")
                    self.wfile.flush()
                except (BrokenPipeError, ConnectionResetError):
                    # Clients often disconnect early once they have what they
                    # need (common with SSE). The request body is already
                    # recorded, so no evidence is lost here.
                    pass
                finally:
                    conn.close()

            do_GET = do_POST = do_PUT = do_DELETE = _forward

        self._server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self._thread = threading.Thread(target=self._server.serve_forever, daemon=True)
        self._thread.start()
        return self

    def __exit__(self, *exc: object) -> None:
        if self._server is not None:
            self._server.shutdown()
            self._server.server_close()

    def _record(self, method: str, path: str, body: bytes) -> None:
        try:
            parsed = json.loads(body) if body else None
        except (json.JSONDecodeError, UnicodeDecodeError):
            parsed = None
        with self._lock:
            self.requests.append({"method": method, "path": path, "body": parsed})

    # ---- assertion helpers -------------------------------------------

    def tool_calls_for(self, *names: str) -> list[str]:
        """Return identifiers of tools in any captured request matching `names`.

        Why match on both `name` and `type`? Because the same capability takes
        different shapes across modes:

        * `claude -p` / Agent SDK: sent as an ordinary custom tool, just
          `{"name": "WebSearch", "input_schema": ...}` — **no type field**.
        * Direct API: sent as an Anthropic server-side tool, shaped like
          `{"type": "web_search_20260209", "name": "web_search"}`.

        Probing for only one shape silently misses the other — the first
        cross-mode trap this repo recorded.
        """
        wanted = {n.lower() for n in names}
        found: list[str] = []
        for req in self.requests:
            body = req.get("body") or {}
            for tool in body.get("tools") or []:
                name = (tool.get("name") or "").lower()
                type_ = (tool.get("type") or "").lower()
                if name in wanted or any(type_.startswith(w) for w in wanted):
                    found.append(tool.get("type") or tool.get("name"))
        return found

    def dump(self, path: str) -> None:
        """Write captured requests as JSONL — the raw evidence for manual review."""
        with open(path, "w", encoding="utf-8") as fh:
            for req in self.requests:
                fh.write(json.dumps(req, ensure_ascii=False) + "\n")
